version: 2
jobs:
  build:
    docker:
      - image: python:3.6.0
    steps:
      - checkout

      - run:
          name: Install Python packages
          command: |
            pip install -r requirements.txt
            pip install coverage
            pip install codecov

      - run:
          command: python plokkeri/generate_passwords.py plokkeri/passwords.py
      - run:
          command: python manage.py test
      - run:
          name: Run coverage
          command: |
            coverage run --source=users,plokkeri manage.py test -v2
            codecov
            coverage report
