version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install Python packages
          command: |
            pip install -r requirements.txt
            pip install coverage
            pip install codecov

      - run:
          name: Generate passwords file
          command: python plokkeri/generate_passwords.py plokkeri/passwords.py

      - run:
          name: Update database tables
          command: |
            python manage.py makemigrations
            python manage.py makemigrations plok
            python manage.py migrate

      - run:
          name: Run unit tests
          command: |
            python manage.py test

      - run:
          name: Run coverage
          command: |
            coverage run --source=users,plok manage.py test -v2
            codecov
            coverage report
