version: 2
jobs:
  build:
    docker:
      - image: python:3.6.1
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Python packages
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install coverage
            pip install codecov

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Generate passwords file
          command: python plokkeri/generate_passwords.py plokkeri/passwords.py

      - run:
          name: Run unit tests
          command: |
            . venv/bin/activate
            python manage.py test

      - run:
          name: Run coverage
          command: |
            . venv/bin/activate
            coverage run --source=users,plok manage.py test -v2
            codecov
            coverage report
