version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages

      - run:
          name: Install Python packages
          command: |
            pip install -r requirements.txt
            pip install coverage
            pip install codecov

      - run:
          name: Generate passwords file
          command: python plokkeri/generate_passwords.py plokkeri/passwords.py

      - run:
          name: Update database tables
          command: |
            python manage.py makemigrations
            python manage.py makemigrations plok
            python manage.py migrate

      - run:
          name: Run unit tests
          command: |
            python manage.py test

      - run:
          name: Run coverage
          command: |
            coverage run --source=users,plok manage.py test -v2
            codecov
            coverage report
