---
- name: Provision server
  hosts: all
  become: true
  vars:
      host: "{{ inventory_hostname }}"

  tasks:
    - name: Check connection
      ping:

    - name: Install required packages
      apt:
        name:
          - nginx
          - git
          - python3-venv
          - python3-full
          - python3-dev
          - build-essential
          - shared-mime-info
          - postfix
        state: present
        update_cache: true

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: true

    - name: Write gunicorn systemd service file
      template:
        src: ./systemd.gunicorn.service.j2
        dest: /etc/systemd/system/gunicorn-{{ app_name }}.service
      notify:
        - Restart gunicorn

    - name: Add nginx config to sites-available
      template:
        src: ./nginx.conf.j2
        dest: /etc/nginx/sites-available/{{ host }}
      notify:
        - Restart nginx

    - name: Add symlink in nginx sites-enabled
      file:
        src: /etc/nginx/sites-available/{{ host }}
        dest: /etc/nginx/sites-enabled/{{ host }}
        state: link
      notify:
        - Restart nginx

  handlers:
    - name: Restart gunicorn
      systemd:
        name: gunicorn-{{ app_name }}
        daemon_reload: true
        enabled: true
        state: restarted

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
