---
- name: prepare server
  hosts: all
  become: true
  vars:
      host: "{{ inventory_hostname }}"

  tasks:
    - name: check connection
      ping:

    - name: install required packages
      apt: pkg={{item}} state=present
      with_items:
        - nginx
        - git
        - python-virtualenv
        - build-essential
        - shared-mime-info
        - python3-dev
        - postfix

    - name: start nginx
      service: name=nginx state=started

    - name: write gunicorn systemd service script
      template:
          src=./systemd.gunicorn.service.j2
          dest=/etc/systemd/system/gunicorn-{{ app_name }}.service
      notify:
          - restart gunicorn

    - name: add nginx config to sites-available
      template:
          src=./nginx.conf.j2
          dest=/etc/nginx/sites-available/{{ host }}
      notify:
          - restart nginx

    - name: add symlink in nginx sites-enabled
      file:
          src=/etc/nginx/sites-available/{{ host }}
          dest=/etc/nginx/sites-enabled/{{ host }}
          state=link
      notify:
          - restart nginx

  handlers:
    - name: restart gunicorn
      systemd:
          name=gunicorn-cvdb
          daemon_reload=yes
          enabled=yes
          state=restarted

    - name: restart nginx
      service:  name=nginx state=restarted
